import { uuid, timestamp } from "../../utils";

/**
 * sudo -u postgres psql -c "CREATE USER ${ZOMBI_DB_USER} WITH PASSWORD '${ZOMBI_DB_PASS}';"
 * sudo -u postgres psql -c "CREATE DATABASE ${ZOMBI_DB_NAME} OWNER=${ZOMBI_DB_USER};"
 */

const create_schema = (table_prefix = "") => {

    const commands = [];

    commands.push(`drop table if exists ${table_prefix}groups`);
    commands.push(`drop table if exists ${table_prefix}groups_to_modules`);
    commands.push(`drop table if exists ${table_prefix}groups_to_users`);
    commands.push(`drop table if exists ${table_prefix}users`);

    commands.push("create sequence if not exists zombi_seq start 100");

    const admin_user_uuid = uuid();
    const admin_group_uuid = uuid();

    commands.push(`create table if not exists ${table_prefix}groups
    (
        id uuid not null
            constraint ${table_prefix}groups_pk primary key,
        group_name varchar(120) not null,
        description varchar(2000),
        created_by uuid not null,
        created_ts integer not null
    )`);

    commands.push(`
        INSERT INTO ${table_prefix}groups (
            id,
            group_name, 
            description, 
            created_by, 
            created_ts
        ) VALUES (
            '${admin_group_uuid}', 
            'ADMIN', 
            'Default Administrators group', 
            '${admin_user_uuid}',
            ${timestamp()}
        )`
    );

    commands.push(`create table if not exists ${table_prefix}groups_to_users
    (
        id uuid not null
            constraint ${table_prefix}groups_to_users_pk
                primary key,
        group_id uuid not null,
        user_id uuid not null,
        created_by uuid not null,
        created_ts integer not null
    )`);

    commands.push(`
        INSERT INTO ${table_prefix}groups_to_users (
            id, 
            group_id, 
            user_id, 
            created_by, 
            created_ts
        ) VALUES (
            '${uuid()}',
            '${admin_group_uuid}', 
            '${admin_user_uuid}',
            '${admin_user_uuid}',
            ${timestamp()}
        )`
    );

    commands.push(`create table if not exists ${table_prefix}groups_to_modules
    (
        id uuid not null
            constraint ${table_prefix}groups_to_modules_pk
                primary key,
        group_id uuid not null,
        module_name varchar(200) not null,
        created_by uuid not null,
        created_ts integer not null
    )`);

    commands.push(`create table if not exists ${table_prefix}users
    (
        id uuid not null
            constraint ${table_prefix}users_pk
                primary key,
        username varchar(120) UNIQUE not null CHECK (username <> ''),
        fullname varchar(100) UNIQUE not null CHECK (fullname <> ''),
        email varchar(120) UNIQUE not null CHECK (email <> ''),
        password varchar(60) not null CHECK (password <> ''),
        timezone varchar(120),
        country varchar(2),
        language varchar(2),
        enabled varchar(1) default 'Y'::character varying not null,
        created_by uuid not null,
        created_ts integer not null,
        password_recovery_token varchar(256) default NULL::character varying,
        password_recovery_ts integer
    )`);

    commands.push(`
        INSERT INTO ${table_prefix}users (
            id, 
            username, 
            fullname, 
            email, 
            password, 
            timezone, 
            country, 
            language, 
            enabled, 
            created_by, 
            created_ts
        ) VALUES (
            '${admin_user_uuid}',
            'system', 
            'SYSTEM', 
            'zombidevelopment@gmail.com', 
            '$2a$10$KCvG0jWj0ZZuGAGxMmjcX.m199FlPLM.NFRcn6cYvY7FUOe0fNXwW', 
            'America/Argentina/Buenos_Aires',
            'AR',
            'es',
            'Y',
            '${admin_user_uuid}',
            ${timestamp()}
        ),
        (
            '${uuid()}', 
            'test', 
            'Test User', 
            'none@mail.com', 
            '$2a$10$KCvG0jWj0ZZuGAGxMmjcX.m199FlPLM.NFRcn6cYvY7FUOe0fNXwW', 
            'America/Argentina/Buenos_Aires',
            'AR',
            'es',
            'Y',
            '${admin_user_uuid}',
            ${timestamp()}
        )`
    );

    return commands;
};

export { create_schema };


/* 
    commands.push(`create table if not exists ${table_prefix}users
    (
        id integer not null
            constraint ${table_prefix}users_pk
                primary key
                GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
        username varchar(120) not null,
        fullname varchar(100) not null,
        email varchar(120) default NULL::character varying,
        password varchar(60) default NULL::character varying,
        timezone varchar(120),
        country varchar(2),
        language varchar(2),
        enabled varchar(1) default 'Y'::character varying not null,
        created_by integer not null,
        created_ts integer not null
    )`);

*/