AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Zombi Server SAM Service
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs12.x
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
    ZombiDBUser:
        Description: 'Required. The Database username'
        Type: 'String'
    ZombiDBPass:
        Description: 'Required. The Database password'
        Type: 'String'
    ZombiDBHost:
        Description: 'Required. The Database hostname'
        Type: 'String'
    ZombiDBPort:
        Description: 'Required. The Database port'
        Type: 'String'
    ZombiDBName:
        Description: 'Required. The Database name'
        Type: 'String'
    ZombiDBType:
        Description: 'Required. The Database type'
        Type: 'String'
    ZombiDBPrefix:
        Description: 'Required. The Database prefix'
        Type: 'String'
    ZombiCacheHost:
        Description: 'Required. The Cache host'
        Type: 'String'
    ZombiCachePort:
        Description: 'Required. The Cache port'
        Type: 'String'
    ZombiCachePass:
        Description: 'Required. The Cache password'
        Type: 'String'
    ZombiCacheTLS:
        Description: 'Required. The Cache TLS'
        Type: 'String'
    ZombiLogLevel:
        Description: 'Required. The level of logging'
        Type: 'String'

Resources:
  SmartiumServerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../../server/
      Handler: lambda.server
      VpcConfig:
        SecurityGroupIds:
          - sg-c183fcbd
        SubnetIds:
          - subnet-7bc67432
          - subnet-23db6745
          - subnet-e366ddb8
      Environment: 
        Variables:
            ZOMBI_DB_USER: !Ref ZombiDBUser
            ZOMBI_DB_PASS: !Ref ZombiDBPass
            ZOMBI_DB_HOST: !Ref ZombiDBHost
            ZOMBI_DB_PORT: !Ref ZombiDBPort
            ZOMBI_DB_NAME: !Ref ZombiDBName
            ZOMBI_DB_TYPE: !Ref ZombiDBType
            ZOMBI_DB_PREFIX: !Ref ZombiDBPrefix
            ZOMBI_CACHE_HOST: !Ref ZombiCacheHost
            ZOMBI_CACHE_PORT: !Ref ZombiCachePort
            ZOMBI_CACHE_PASS: !Ref ZombiCachePass
            ZOMBI_CACHE_TLS: !Ref ZombiCacheTLS
            ZOMBI_LOG_LEVEL: !Ref ZombiLogLevel
      Events:
        ZombiServerApi:
          Type: Api
          Properties:
            Path: /server
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ZombiServerApi:
    Description: "API Gateway endpoint URL for Zombi Server"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/*/server/"
  ZombiServerFunction:
    Description: "Zombi Server Lambda Function ARN"
    Value: !GetAtt ZombiServerFunction.Arn
